'use client';

import { motion, useReducedMotion } from 'framer-motion';
import { TrendingUp, Users, Building2, CreditCard, Shield, Car, UserPlus, Gauge } from 'lucide-react';
import { useCountUp } from '@/hooks/use-count-up';
import { cn } from '@/lib/utils';

type VentureTag =
  | 'Prime Digital Solutions'
  | 'Thrifty Tribe'
  | 'ICKY'
  | 'Prime Axis'
  | 'Tentmakers Network';

interface StatItem {
  id: string;
  prefix?: string;
  value: number;
  suffix?: string;
  decimals?: number;
  label: string;
  caption: string;
  venture: VentureTag;
  icon: React.ElementType;
  span?: 'sm' | 'md' | 'lg';
  highlight?: boolean;
}

const heroStat: StatItem = {
  id: 'population',
  value: 4.67,
  decimals: 2,
  suffix: 'M',
  label: 'Panay Island population',
  caption:
    'A captive regional market larger than many national capitals — the foundation beneath every Tentmakers venture.',
  venture: 'Tentmakers Network',
  icon: Users,
  span: 'lg',
};

const secondaryStats: StatItem[] = [
  {
    id: 'msme-count',
    value: 57469,
    label: 'MSME establishments, Western Visayas (DTI)',
    caption: '5th-highest regional concentration in the Philippines.',
    venture: 'Prime Digital Solutions',
    icon: Building2,
    span: 'md',
  },
  {
    id: 'msme-share',
    value: 99.5,
    decimals: 1,
    suffix: '%',
    label: 'of all Philippine businesses are MSMEs',
    caption: 'The backbone of the economy — and the most underserved segment.',
    venture: 'Prime Digital Solutions',
    icon: Gauge,
    span: 'sm',
  },
  {
    id: 'employment',
    value: 63,
    suffix: '%',
    label: 'of national employment generated by MSMEs',
    caption: 'Where the jobs are. Where the growth must reach.',
    venture: 'Tentmakers Network',
    icon: Users,
    span: 'sm',
  },
  {
    id: 'digital-payments',
    value: 57.4,
    decimals: 1,
    suffix: '%',
    label: 'of retail transaction volume is now digital',
    caption: 'The payments rail is built. The storefronts are not.',
    venture: 'Prime Digital Solutions',
    icon: CreditCard,
    span: 'md',
  },
  {
    id: 'insurance-gap',
    value: 2,
    suffix: '%',
    label: 'insurance penetration nationally — under this threshold',
    caption:
      'A protection gap that leaves families one emergency away from financial collapse.',
    venture: 'Prime Axis',
    icon: Shield,
    span: 'md',
    highlight: true,
  },
  {
    id: 'road-accidents',
    value: 31000,
    suffix: '+',
    label: 'road accidents recorded in 2024',
    caption: 'Every figure is a claim, a family, an uncovered loss.',
    venture: 'Prime Axis',
    icon: Car,
    span: 'sm',
  },
  {
    id: 'sme-hiring',
    value: 41,
    suffix: '%',
    label: 'of Philippine SMEs increased headcount in 2024',
    caption: 'More are planning to hire in 2025. Staffing is the bottleneck.',
    venture: 'ICKY',
    icon: UserPlus,
    span: 'sm',
  },
];

function CountUpStat({
  stat,
  className,
}: {
  stat: StatItem;
  className?: string;
}) {
  const { ref, displayValue } = useCountUp({
    end: stat.value,
    decimals: stat.decimals ?? 0,
    duration: 2200,
  });

  return (
    <span
      ref={ref}
      className={cn('tabular-nums', className)}
      aria-label={`${stat.prefix ?? ''}${stat.value}${stat.suffix ?? ''} ${stat.label}`}
    >
      {stat.prefix}
      {displayValue}
      {stat.suffix}
    </span>
  );
}

function StatCard({
  stat,
  index,
}: {
  stat: StatItem;
  index: number;
}) {
  const prefersReducedMotion = useReducedMotion();
  const Icon = stat.icon;

  const spanClass =
    stat.span === 'md'
      ? 'lg:col-span-2'
      : stat.span === 'lg'
        ? 'lg:col-span-3'
        : 'lg:col-span-1';

  return (
    <motion.div
      initial={prefersReducedMotion ? { opacity: 1 } : { opacity: 0, y: 24 }}
      whileInView={prefersReducedMotion ? { opacity: 1 } : { opacity: 1, y: 0 }}
      viewport={{ once: true, margin: '-60px' }}
      transition={{
        duration: 0.6,
        delay: prefersReducedMotion ? 0 : index * 0.08,
        ease: [0.22, 1, 0.36, 1],
      }}
      className={cn(
        'group relative flex flex-col justify-between rounded-xl border p-5 transition-all duration-300 hover:shadow-lg sm:p-6',
        spanClass,
        stat.highlight
          ? 'border-amber/30 bg-amber/[0.04] hover:border-amber/50 hover:shadow-amber/[0.06]'
          : 'border-border bg-card hover:border-amber/30 hover:shadow-navy/[0.03]'
      )}
    >
      {stat.highlight && (
        <div
          className="absolute inset-x-0 top-0 h-0.5 rounded-t-xl bg-amber"
          aria-hidden="true"
        />
      )}
      <div className="flex items-start justify-between gap-3">
        <div
          className={cn(
            'flex h-9 w-9 shrink-0 items-center justify-center rounded-lg transition-colors duration-200',
            stat.highlight
              ? 'bg-amber/15 text-amber'
              : 'bg-secondary text-muted-foreground group-hover:bg-amber/10 group-hover:text-amber'
          )}
        >
          <Icon className="h-4 w-4" aria-hidden="true" />
        </div>
        <span
          className={cn(
            'text-[10px] font-semibold uppercase tracking-[0.14em]',
            stat.highlight ? 'text-amber' : 'text-muted-foreground/70'
          )}
        >
          {stat.venture}
        </span>
      </div>

      <div className="mt-4">
        <CountUpStat
          stat={stat}
          className={cn(
            'block text-3xl font-bold leading-none tracking-tight sm:text-4xl',
            stat.highlight ? 'text-amber' : 'text-foreground'
          )}
        />
        <p className="mt-2 text-sm font-medium leading-snug text-foreground">
          {stat.label}
        </p>
      </div>

      <p className="mt-3 text-xs leading-relaxed text-muted-foreground">
        {stat.caption}
      </p>
    </motion.div>
  );
}

function HeroStatBlock() {
  const prefersReducedMotion = useReducedMotion();

  return (
    <motion.div
      initial={prefersReducedMotion ? { opacity: 1 } : { opacity: 0, x: -32 }}
      whileInView={prefersReducedMotion ? { opacity: 1 } : { opacity: 1, x: 0 }}
      viewport={{ once: true, margin: '-80px' }}
      transition={{ duration: 0.8, ease: [0.22, 1, 0.36, 1] }}
      className="group relative flex h-full flex-col justify-between overflow-hidden rounded-2xl bg-navy p-7 text-white transition-shadow duration-300 hover:shadow-xl hover:shadow-navy/15 sm:p-9 lg:col-span-3 lg:row-span-2"
    >
      {/* Decorative grid */}
      <div
        className="pointer-events-none absolute inset-0 opacity-[0.06]"
        aria-hidden="true"
        style={{
          backgroundImage:
            'linear-gradient(to right, white 1px, transparent 1px), linear-gradient(to bottom, white 1px, transparent 1px)',
          backgroundSize: '52px 52px',
        }}
      />
      {/* Amber glow */}
      <div
        className="pointer-events-none absolute -right-24 -top-24 h-72 w-72 rounded-full bg-amber/15 blur-3xl transition-opacity duration-500 group-hover:opacity-100"
        aria-hidden="true"
      />

      <div className="relative z-10 flex items-center gap-2">
        <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-white/10">
          <Users className="h-4 w-4 text-amber" aria-hidden="true" />
        </span>
        <span className="text-[11px] font-semibold uppercase tracking-[0.16em] text-white/60">
          Tentmakers Network
        </span>
      </div>

      <div className="relative z-10 mt-8">
        <CountUpStat
          stat={heroStat}
          className="block text-6xl font-bold leading-[0.9] tracking-tight text-amber sm:text-7xl lg:text-[5.5rem]"
        />
        <h3 className="mt-4 text-lg font-semibold leading-snug text-white sm:text-xl">
          {heroStat.label}
        </h3>
        <p className="mt-3 max-w-sm text-sm leading-relaxed text-white/65">
          {heroStat.caption}
        </p>
      </div>

      <div className="relative z-10 mt-8 flex items-center gap-2 border-t border-white/10 pt-5">
        <TrendingUp className="h-4 w-4 text-amber" aria-hidden="true" />
        <span className="text-xs font-medium text-white/50">
          The demand side of the equation — every venture scales into this base.
        </span>
      </div>
    </motion.div>
  );
}

export default function MarketOpportunity() {
  const prefersReducedMotion = useReducedMotion();

  return (
    <section
      id="market-opportunity"
      className="relative w-full bg-background py-24 sm:py-32"
      aria-labelledby="market-opportunity-heading"
    >
      <div
        className="absolute inset-x-0 top-0 mx-auto h-px max-w-6xl bg-gradient-to-r from-transparent via-border to-transparent"
        aria-hidden="true"
      />

      <div className="mx-auto max-w-6xl px-5 sm:px-6 lg:px-8">
        {/* Header */}
        <motion.div
          initial={prefersReducedMotion ? { opacity: 1 } : { opacity: 0, y: 24 }}
          whileInView={prefersReducedMotion ? { opacity: 1 } : { opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-80px' }}
          transition={{ duration: 0.7, ease: [0.22, 1, 0.36, 1] }}
          className="max-w-3xl"
        >
          <div className="flex items-center gap-2.5">
            <span className="h-px w-8 bg-amber" aria-hidden="true" />
            <span className="text-xs font-semibold uppercase tracking-[0.18em] text-amber">
              Your Market
            </span>
          </div>
          <h2
            id="market-opportunity-heading"
            className="mt-5 font-display text-3xl font-bold leading-[1.1] tracking-tight text-foreground sm:text-4xl lg:text-[2.75rem]"
          >
            A 4.67-million-person market,{' '}
            <span className="text-amber">yours to serve</span>
          </h2>
          <p className="mt-5 max-w-2xl text-base leading-relaxed text-muted-foreground sm:text-lg">
            Panay Island is home to 4.67 million people, and Western Visayas counts 57,469 MSME
            establishments — the fifth-highest regional concentration in the
            Philippines. Nationally, MSMEs make up 99.5% of all businesses and
            generate roughly 63% of employment, yet the gap between basic
            connectivity and real digital presence, savings tools, insurance
            coverage, and reliable staffing remains wide. Each figure maps
            directly onto the gap one of the five Tentmakers ventures is built
            to close — and the Readiness Score ensures members build real
            capability before accessing each venture.
          </p>
        </motion.div>

        {/* Stat grid */}
        <div className="mt-12 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:mt-16 lg:grid-cols-5 lg:gap-5">
          <HeroStatBlock />

          {secondaryStats.map((stat, index) => (
            <StatCard key={stat.id} stat={stat} index={index + 1} />
          ))}
        </div>

        {/* Closing callout */}
        <motion.div
          initial={prefersReducedMotion ? { opacity: 1 } : { opacity: 0, y: 24 }}
          whileInView={prefersReducedMotion ? { opacity: 1 } : { opacity: 1, y: 0 }}
          viewport={{ once: true, margin: '-60px' }}
          transition={{ duration: 0.7, delay: 0.15, ease: [0.22, 1, 0.36, 1] }}
          className="relative mt-6 overflow-hidden rounded-2xl border border-navy/10 bg-navy p-7 text-white sm:mt-8 sm:p-10 lg:p-12"
        >
          <div
            className="absolute left-0 top-0 h-full w-1 bg-amber"
            aria-hidden="true"
          />
          <div
            className="pointer-events-none absolute -bottom-24 -right-12 h-56 w-56 rounded-full bg-amber/10 blur-3xl"
            aria-hidden="true"
          />
          <div className="relative z-10 flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between">
            <p className="max-w-2xl text-lg font-medium leading-relaxed text-white/90 sm:text-xl">
              Each gap is a venture.{' '}
              <span className="text-white/60">
                Prime Digital Solutions serves the storefront gap. Thrifty Tribe
                serves the savings gap. ICKY serves the staffing gap. Prime Axis
                serves the protection gap. Tentmakers Network ties them together.
              </span>
            </p>
            <div className="flex shrink-0 items-center gap-3 lg:flex-col lg:items-end">
              {(
                [
                  'Prime Digital Solutions',
                  'Thrifty Tribe',
                  'ICKY',
                  'Prime Axis',
                  'Tentmakers Network',
                ] as VentureTag[]
              ).map((v, i) => (
                <span
                  key={v}
                  className={cn(
                    'whitespace-nowrap text-xs font-semibold tracking-wide',
                    i === 4 ? 'text-amber' : 'text-white/40'
                  )}
                >
                  {v}
                </span>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </section>
  );
}
